import React from "react";
import { motion } from "motion/react";

const Terms = () => {
  return (
    <div className="min-h-screen px-6 md:px-16 py-20 text-white">

      {/* HERO */}
      <motion.div
        initial={{ opacity: 0, y: 40 }}
        animate={{ opacity: 1, y: 0 }}
        className="max-w-4xl mx-auto text-center mb-16"
      >
        <h1 className="text-4xl md:text-5xl font-bold mb-4">
          Terms of Service
        </h1>
        <p className="text-zinc-400">
          Please read these terms carefully before using Prompt2Site.
        </p>
      </motion.div>

      {/* CONTENT */}
      <div className="max-w-4xl mx-auto space-y-10 text-zinc-300 leading-relaxed">

        <Section title="1. Acceptance of Terms">
          By accessing or using Prompt2Site, you agree to be bound by these
          Terms of Service. If you do not agree, please do not use our platform.
        </Section>

        <Section title="2. Use of the Service">
          You agree to use the service only for lawful purposes and not to misuse
          the platform in any way that could harm others or disrupt functionality.
        </Section>

        <Section title="3. User Accounts">
          You are responsible for maintaining the confidentiality of your account
          and for all activities that occur under your account.
        </Section>

        <Section title="4. Generated Content">
          The websites generated by AI are provided as-is. You are responsible
          for reviewing and validating all generated content before use.
        </Section>

        <Section title="5. Payments & Subscriptions">
          All payments are non-refundable unless otherwise stated. Subscription
          plans may change over time.
        </Section>

        <Section title="6. Limitation of Liability">
          Prompt2Site is not liable for any damages arising from the use of the
          platform, including but not limited to data loss or business impact.
        </Section>

        <Section title="7. Termination">
          We reserve the right to suspend or terminate access to the service at
          any time if terms are violated.
        </Section>

        <Section title="8. Changes to Terms">
          We may update these terms from time to time. Continued use of the
          platform means you accept the updated terms.
        </Section>

        <Section title="9. Contact">
          If you have any questions, please contact us at support@prompt2site.com
        </Section>

      </div>
    </div>
  );
};

export default Terms;


const Section = ({ title, children }) => {
  return (
    <div className="p-6 rounded-xl bg-white/5 border border-white/10 backdrop-blur-xl">
      <h2 className="text-xl font-semibold mb-3 text-white">{title}</h2>
      <p className="text-sm text-zinc-400">{children}</p>
    </div>
  );
};